[package]
name = "wasm-worker-gloo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo-worker = { version = "0.5.0", features = ["futures"] }
log = "0.4.22"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
wasm-logger = "0.2.0"
